// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9wcmaOQF25QxJNKBtZzYg4uRuI4E-HZM',
    appId: '1:66171560086:web:67cc1033d80f0bab9fe2b7',
    messagingSenderId: '66171560086',
    projectId: 'mainmain-bca20',
    authDomain: 'mainmain-bca20.firebaseapp.com',
    storageBucket: 'mainmain-bca20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNewGUQ5G3B2c0ib6-O5fAQrL9IrelcYM',
    appId: '1:66171560086:android:7656edbcbad501409fe2b7',
    messagingSenderId: '66171560086',
    projectId: 'mainmain-bca20',
    storageBucket: 'mainmain-bca20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA285lukRl083JeeCBBZP-CSGtJuAeu1tk',
    appId: '1:66171560086:ios:3e6589d77be3e2079fe2b7',
    messagingSenderId: '66171560086',
    projectId: 'mainmain-bca20',
    storageBucket: 'mainmain-bca20.appspot.com',
    iosClientId: '66171560086-mhkqjd5vu4cte7bbvll9o8nv8ej4cf56.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA285lukRl083JeeCBBZP-CSGtJuAeu1tk',
    appId: '1:66171560086:ios:0dfffd4056abb6ef9fe2b7',
    messagingSenderId: '66171560086',
    projectId: 'mainmain-bca20',
    storageBucket: 'mainmain-bca20.appspot.com',
    iosClientId: '66171560086-n9mv08chl7uj0qg3aodl0412763m0mkf.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.demo.RunnerTests',
  );
}
